### ISSUE TITLE
Comments in xxxParameterSets sections of objects fail Env Instance generation

### ISSUE THREAD

**Issue by popoveugene** [Netcracker/qubership-envgene#124]
### Describe the bug

When there are commented lines in the deployParameterSets sections (possibly also in e2e and tech) of an NS template (possibly Cloud as well), it results in the generation of an NS object that is not schema-valid.
This might be related to the template override feature.

Along with the bug fix it is necessary to:

1. **Prepare a test data for smoke tests to check the feature**

### To Reproduce

**How to reproduce**
1. Use Template Descriptor:

```
...
namespaces:
  - template_path: <path-to-ns-template>
    template_override:
      deployParameterSets:
        - paramset-A
...
```

2. Use Namespace Template

```
...
deployParameterSets:
# comment
- paramset-B
...
```

3. Run Env Instance generation

**ER:**
Namespace object:

```
deployParameterSets: []
# comment
```

**AR:**
Namespace object:

```
deployParameterSets:
# comment
[]
```

### Version

1.1.12
