### ISSUE TITLE
Effective Set Generator - Missing Nested Fields in List Structures

### ISSUE THREAD

**Issue by kannann1** [Netcracker/qubership-envgene#157]
### Describe the bug

# Bug: Effective Set Generator Omits Nested Fields in List Structures

## Problem

The Effective Set Generator is failing to preserve all nested fields when processing list structures in YAML configurations. Specifically, when a list contains dictionaries with nested fields that mix both credential and non-credential parameters, certain fields are being omitted in the final rendered output. This issue only manifests when complex nested list structures contain both types of parameters together.

## Observed Behavior

When processing YAML configurations that contain list structures with nested dictionaries, the generator fails to preserve certain fields in the final output:

- Nested configuration fields within list items are partially or completely missing in the output
- Some nested dictionary structures are incorrectly rendered as empty dictionaries (`{}`) instead of preserving their content
- This specifically occurs when a list item contains both credential-related fields (fields with values containing credential macros) and regular configuration fields in the same nested structure
- The issue is structural and not tied to specific field names - it will affect any nested fields within list structures that mix credentials and regular parameters

## Expected Behavior

All nested fields should be preserved in the final output, regardless of their position in the hierarchy or whether they're within list structures.

## Reproduction Steps

1. Create a deployment parameters file with a list structure containing nested dictionaries, similar to:

```yaml
services:
  monitoring:
    agent:
      endpoints:
        - url: "https://metrics-collector.example.com/write"
          authentication:
            createSecret:
              username: "${creds.get('metrics-auth').username}"
              password: "${creds.get('metrics-auth').password}"
              secretName: "metrics-collector-auth"
          tlsSettings:
            insecureSkipVerify: true
        - relabelConfig:
            - if: '{cluster=""}'
              replacement: "production"
              targetLabel: "cluster"
          url: "http://local-metrics.monitoring.svc:8429/write"
```

2. Run the Effective Set Generator

3. Observe that `secretName` and `insecureSkipVerify` fields are missing or incorrectly rendered in the output both in credentials.yaml and deployParameters.yaml.

### Version

v1.2.0
