### ISSUE TITLE
Validation to Fail Fast on Missing Credentials before Effective Set Generation

### ISSUE THREAD

**Issue by kannann1** [Netcracker/qubership-envgene#159]
### Is your feature request related to a problem? Please describe

Currently, when credentials are referenced in templates but not defined in the environment credentials store, the Envgen inventory generation pipeline assigns "envgeneNullValue" as a placeholder and continues execution. 

Example from the platform-monitoring template:

```yaml
createSecret:
  username: "${creds.get(\"main-cluster-creds\").username}"
  password: "${creds.get(\"main-cluster-creds\").password}"
  secretName: "main-cluster-basicauth"
```

When credentials are missing, the generated output is:

```yaml
createSecret:
  password: "envgeneNullValue" # from application level
  username: "envgeneNullValue" # from application level
```

We need to implement validation of credentials before the effective set generation process begins.

### Describe the solution you'd like

1. Add a validation step that checks the processed credential values before finalizing the effective set generation
2. Create a new validation function that scans for "envgeneNullValue" in the credential values
3. Implement a failure mechanism that stops the process and provides a clear error message when "envgeneNullValue" is detected
