### ISSUE TITLE
Add `Solution Structure` template variable

### ISSUE THREAD

**Issue by popoveugene** [Netcracker/qubership-envgene#17]
### Is your feature request related to a problem? Please describe

To describe integration (integrations between applications within the solution) parameters in an Environment Template , there is a lack of information about the solution's structure—specifically, the applications that are part of it and the namespaces of these applications.

### Describe the solution you'd like

**Proposed:**

1. Introduce [`current_env.solution_structure`](https://github.com/popoveugene/qubership-envgene/blob/add-sd-to-render-context/docs/template-macros.md#current_envsolution_structure) template rendering variable

2. During the release EnvGene version with implementation of the change merge [pull request](https://github.com/Netcracker/qubership-envgene/pull/18) that includes docs

**Upon fulfilling these requirements:**

1. This variable should be placed in the rendering context of the environment template.
2. The structure of the variable should be:

```yaml
<application-name-A>:
  deployPostfix: <deploy-postfix-value-A>
  namespace: <namespace-A>
  version: <application-version-A>
<application-name-B>:
  deployPostfix: <deploy-postfix-value-B>
  namespace: <namespace-B>
  version: <application-version-B>
```

3. The value of the variable should be derived from the `application` attribute of the file `/configuration/environments/<CLUSTER-NAME>/<ENV-NAME>/solution-descriptor/sd.yml`:

```yaml
applications:
  - version: <application-name-A>:<application-version-A>
    deployPostfix: <deploy-postfix-value-A>
  - version:<application-name-B>:<application-version-B>
    deployPostfix: <deploy-postfix-value-B>
```
4. The value of the `namespace` attribute in this variable should be obtained from the `name` attribute of the **already rendered** `Namespace` object. The definition of this **already rendered** `Namespace` object is located at `/configuration/environments/<CLUSTER-NAME>/<ENV-NAME>/Namespaces/<deployPostfix>/namespace.yml`.
