### ISSUE TITLE
extra quotes in key

### ISSUE THREAD

**Issue by popoveugene** [Netcracker/qubership-envgene#212]
### Describe the bug

при использовании темплейт оверрайда в отрендеренном неймспейсе появляются кавычки у ключа

### To Reproduce

1. Create SD in the env instance:

```yaml
version: 2.1
type: deploy
applications:
  - version: "core-app:release-1.2.4-20240402.110146-1-RELEASE"
    deployPostfix: "core"
  - version: "core-app:release-1.2.4-20240402.110146-1-RELEASE"
    deployPostfix: "bss"
  - version: "bss-app:master-20240412.120655-192"
    deployPostfix: "bss"
  - version: "core-app:release-1.2.4-20240402.110146-1-RELEASE"
    deployPostfix: "oss"
  - version: "oss-app:release-2024-2-1.01.026"
    deployPostfix: "oss"
  - version: "billing-app:release-2024-1-1.011.013-RELEASE"
    deployPostfix: "billing"
```

2. Set in the template descriptor:

```
  - template_path: "{{ templates_dir }}/env_templates/composite/namespaces/bss.yml.j2"
    template_override:
      deployParameters:
        oss_ns: "{{ current_env.solution_structure['oss-app']['oss'].namespace }}"
      profile:
        name: prod_bss_override
        baseline: prod
```

3. Run env build

ER:
In the rendered env:
```
oss_ns: "env-01-oss"
```

AR:
In the rendered env:
```
'oss_ns': "env-01-oss"
```

Note: This case is already covered by smoke tests. In etalon result set wrong key - 'oss_ns'. Please update test data after the fix 

### Version

1.2.8
