### ISSUE TITLE
Update `Solution Structure` template variable

### ISSUE THREAD

**Issue by popoveugene** [Netcracker/qubership-envgene#30]
### Is your feature request related to a problem? Please describe

Существующая структура не поддерживает кейс, когда один и тот же апп находится в разных неймспейсах

### Describe the solution you'd like

Proposed:

1. Update `Solution Structure` variable according to:

```yaml
<application-name-A>:
  <deploy-postfix-A>:
    version: <application-version-A>
    namespace: <namespace-A>
<application-name-B>:
  <deploy-postfix-B>:
    version: <application-version-B>
    namespace: <namespace-B>
  <deploy-postfix-C>:
    version: <application-version-C>
    namespace: <namespace-C>
```

2. Introduce logic - If the corresponding `Namespace` object is not found, the `namespace` value is set to `Null`.

2. During the release EnvGene version with implementation of the change merge https://github.com/Netcracker/qubership-envgene/pull/45 that includes docs
